### PR TITLE
Added useful ML and DL Examples

### PR DESCRIPTION
**Pull request by nathzi1505**
Useful DL and ML examples which may come in handy in various use-cases.

### CODE REVIEW

**Comment by nathzi1505** [comment]
Hope those examples are helpful. Please feel free to merge if you find them useful. Happy Hacking!

**Comment by pranav2012** [comment]
@nathzi1505 add a readme file with all the images you have entered and all the  machine learning models you have added that will be great:+1:

**Comment by nathzi1505** [comment]
Can u add the hacktoberfest-label to this

**Comment by pranav2012** [comment]
Sure

**Pull request merged**
